<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.20348.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <SupportedOSPlatformVersion>10.0.20348.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Attributes.cs" />
    <Compile Remove="Converters.cs" />
    <Compile Remove="CustomViewModel.cs" />
    <Compile Remove="ItemsControlTemplateSelector.cs.cs" />
    <Compile Remove="PropertyTemplateSelector.cs" />
    <Compile Remove="S100AttributeEditor.xaml.cs" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="S100AttributeEditor.xaml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\UI\S100Framework.WPF.S100AttributeEditor\S100Framework.WPF.S100AttributeEditor.csproj" />
  </ItemGroup>

</Project>
