<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.20348.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="s100ed9.gdb\**" />
    <Content Remove="s100ed9.gdb\**" />
    <EmbeddedResource Remove="s100ed9.gdb\**" />
    <None Remove="s100ed9.gdb\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="8.0.20" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\S100Framework.ArcGIS.Core\S100Framework.ArcGIS.Core.csproj" />
    <ProjectReference Include="..\..\Core\S100Framework.Catalogues\S100Framework.Catalogues.csproj" />
    <ProjectReference Include="..\..\Core\S100Framework.ProductCatalogue\S100Framework.ProductCatalogue.csproj" />
    <ProjectReference Include="..\..\Core\S100Framework.YAML\S100Framework.YAML.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ArcGIS.Core">
      <HintPath>C:\Program Files\ArcGIS\Pro\bin\ArcGIS.Core.dll</HintPath>
    </Reference>
    <Reference Include="ArcGIS.CoreHost">
      <HintPath>C:\Program Files\ArcGIS\Pro\bin\ArcGIS.CoreHost.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="s100ed9.gdb.zip">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
