<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.20348.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>S100Framework.WPF</RootNamespace>
	<UseWPF>true</UseWPF>
	<Platforms>AnyCPU</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Images\minus.png" />
    <None Remove="Images\plus.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\S100Framework.Catalogues\S100Framework.Catalogues.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\minus.png" />
    <Resource Include="Images\plus.png" />
  </ItemGroup>

</Project>
