<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.20348.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
	<UseWPF>true</UseWPF>
	<Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Artifacts\**" />
    <EmbeddedResource Remove="Artifacts\**" />
    <None Remove="Artifacts\**" />
    <Page Remove="Artifacts\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="TestClassBuilder.cs" />
    <Compile Remove="UnitTestDataset.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="JsonFlatten" Version="1.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="Pluralize.NET.Core" Version="1.0.0" />
    <PackageReference Include="SharpZipLib" Version="1.4.2" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Text.Json" Version="8.0.6" />
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Samples\S201\" />
    <Folder Include="Samples\S131\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\artifacts\Product Specifications\S-131 Marine Harbour Infrastructure\samples\DKAAL\S100_ROOT\S-131\DATASET_FILES\DK00\131DK00_DKAAL.GML" Link="Samples\S131\131DK00_DKAAL.GML">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Core\S100Framework.ArcGIS.Core\S100Framework.ArcGIS.Core.csproj" />
    <ProjectReference Include="..\..\..\src\Core\S100Framework.Catalogues\S100Framework.Catalogues.csproj" />
    <ProjectReference Include="..\..\..\src\Core\S100Framework.GML\S100Framework.GML.csproj" />
    <ProjectReference Include="..\..\..\src\Core\S100Framework.YAML\S100Framework.YAML.csproj" />
    <ProjectReference Include="..\..\..\src\UI\S100Framework.WPF\S100Framework.WPF.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ArcGIS.Core">
      <HintPath>C:\Program Files\ArcGIS\Pro\bin\ArcGIS.Core.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>True</Private>	  
    </Reference>
    <Reference Include="ArcGIS.CoreHost">
      <HintPath>C:\Program Files\ArcGIS\Pro\bin\ArcGIS.CoreHost.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>True</Private>	  
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="s100ed6.gdb.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="s100ed8.gdb.zip">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
