<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.20348.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
	<UseWPF>true</UseWPF>
	<Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Artifacts\**" />
    <EmbeddedResource Remove="Artifacts\**" />
    <None Remove="Artifacts\**" />
    <Page Remove="Artifacts\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DomainModelBase.cs" />
    <Compile Remove="TestClassBuilder.cs" />
    <Compile Remove="UnitTestDataset.cs" />
    <Compile Remove="UnitTestRoslyn.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Pluralize.NET.Core" Version="1.0.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Samples\S201\" />
    <Folder Include="Samples\S131\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\artifacts\Product Specifications\S-131 Marine Harbour Infrastructure\samples\DKAAL\S100_ROOT\S-131\DATASET_FILES\DK00\131DK00_DKAAL.GML" Link="Samples\S131\131DK00_DKAAL.GML">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="..\..\..\artifacts\Product Specifications\S-201 Aids to Navigation Information\1.1.0\201CAtestgml_Inline.gml" Link="Samples\S201\201CAtestgml_Inline.gml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Application\VortexRoslyn\VortexRoslyn.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="ArcGIS.Core">
      <HintPath>C:\Program Files\ArcGIS\Pro\bin\ArcGIS.Core.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>True</Private>	  
    </Reference>
    <Reference Include="ArcGIS.CoreHost">
      <HintPath>C:\Program Files\ArcGIS\Pro\bin\ArcGIS.CoreHost.dll</HintPath>
      <CopyLocal>False</CopyLocal>
      <Private>True</Private>	  
    </Reference>
  </ItemGroup>

</Project>
