<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Editors.cs" />
    <Compile Remove="S-124_ViewModel.g.cs" />
    <Compile Remove="S-901_Custom.cs" />
    <Compile Remove="S-901_ViewModel.g.cs" />
    <Compile Remove="S-902_Custom.cs" />
    <Compile Remove="S-903_Custom.cs" />
    <Compile Remove="S-904_Custom.cs" />
    <Compile Remove="S-905_Custom.cs" />
    <Compile Remove="S-922_ViewModel.g.cs" />
    <Compile Remove="S-924_ViewModel.g.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="4.7.25104.5739" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Enrichers.ExceptionData" Version="1.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Core\S100Framework.Catalogues\S100Framework.Catalogues.csproj" />
    <ProjectReference Include="..\..\..\src\UI\S100Framework.WPF\S100Framework.WPF.csproj" />
  </ItemGroup>

</Project>
